alias ll="ls -lF"
alias lll="ls -l | less"
alias gb="git branch"
alias gl="git log --oneline --decorate -12"
alias gll="git log --oneline --decorate | less"
alias gs="git status"
alias dst="source def_set-title"
