#
#	Global configuration for SNAP makefiles
#

GLIB = glib-core
SNAP = snap-core
GLIBADV = glib-adv
SNAPADV = snap-adv
SNAPEXP = snap-exp

CGLIB = ../snap/$(GLIB)
CSNAP = ../snap/$(SNAP)

EXGLIB = ../../snap/$(GLIB)
EXSNAP = ../../snap/$(SNAP)
EXGLIBADV = ../../snap/$(GLIBADV)
EXSNAPADV = ../../snap/$(SNAPADV)
EXSNAPEXP = ../../snap/$(SNAPEXP)

UNAME := $(shell uname)

# Linux flags
CC = g++
CXXFLAGS += -std=c++98 -Wall
CXXFLAGS += -O3 -DNDEBUG -fopenmp
# turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
CXXFLAGS += -g -rdynamic
CXXFLAGS += -ggdb
# turn on for OpenMP
CXXOPENMP = 
LDFLAGS +=
LIBS += -lrt
