#! /usr/bin/env python

import sys


def main():
    if len(sys.argv) != 2:
        print 'usage: python make_list.py <infile>'
        sys.exit(1)

    # Pass the json file building a [json] list.
    firstline = True
    with open(sys.argv[1], 'r') as infile:
        for line in infile:
            if firstline:
                print '[',
                print line,
                firstline = False
            else:
                print ','
                print line,
        print ']'


if __name__ == '__main__':
    main()
